# Generated by Django 4.0.3 on 2023-03-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_newcontactevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendEmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('content', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='buysubscriptioninterestcontactevent',
            name='requirements',
        ),
        migrations.AddField(
            model_name='user',
            name='employee_size',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
