# Generated by Django 4.0.3 on 2023-03-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_sendemailevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buysubscriptioninterestcontactevent',
            name='requirements',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
